#!/usr/bin/env bash
# Generate the xiond Homebrew formulas for a release from one template.
#
#   ./generate.sh <tag>          e.g. ./generate.sh v30.0.0
#
# Writes:
#   Formula/xiond.rb             (stable releases only)
#   Formula/xiond@MAJOR.rb       e.g. xiond@30.rb
#   Formula/xiond@VERSION.rb     e.g. xiond@30.0.0.rb
#
# Pre-releases (-rc, -alpha, -beta, -preview, -dev) update only the versioned
# formulas, so `brew install xiond` keeps serving the latest stable release.
#
# Checksums are read from the release's checksums.txt on GitHub. Supports the
# modern (v15+) asset naming: xiond_<version>_<os>_<arch>.tar.gz.
#
# Portable to macOS out of the box: plain POSIX tools only, no GNU sed or
# bash-4 features (the stock /bin/bash is 3.2).
set -euo pipefail

TAG="${1:?usage: $0 <tag>}"
TAG="v${TAG#v}"

SEMVER_RE='^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.]+)?$'
if ! [[ "$TAG" =~ $SEMVER_RE ]]; then
  echo "error: '$TAG' is not a release tag (expected vMAJOR.MINOR.PATCH[-suffix])" >&2
  exit 2
fi

VERSION="${TAG#v}"
MAJOR="${VERSION%%.*}"

if [ "$MAJOR" -le 14 ]; then
  echo "error: only releases v15+ use the current asset naming; older formulas are kept as committed" >&2
  exit 1
fi

IS_PRERELEASE=false
if echo "$VERSION" | grep -qiE -- '-(rc|alpha|beta|preview|dev)'; then
  IS_PRERELEASE=true
fi

# Ruby class suffix: drop dots, camelize pre-release segments
# (29.0.1 -> 2901, 29.0.0-rc1 -> 2900Rc1).
CLASS_VERSION=$(echo "$VERSION" | tr -d '.' | awk -F- '{
  out = $1
  for (i = 2; i <= NF; i++) out = out toupper(substr($i, 1, 1)) substr($i, 2)
  print out
}')

echo "Downloading checksums for ${TAG}..."
CHECKSUMS=$(curl -fsSL "https://github.com/burnt-labs/xion/releases/download/${TAG}/xiond-${VERSION}-checksums.txt")

checksum() {
  # Single awk call: a grep in this pipeline would trip pipefail on a missing
  # entry before the per-platform "not found" checks below get to report it.
  echo "$CHECKSUMS" | awk -v want="xiond_${VERSION}_$1.tar.gz" '$2 == want { print $1 }'
}
DARWIN_AMD64=$(checksum darwin_amd64)
DARWIN_ARM64=$(checksum darwin_arm64)
LINUX_AMD64=$(checksum linux_amd64)
LINUX_ARM64=$(checksum linux_arm64)
for v in DARWIN_AMD64 DARWIN_ARM64 LINUX_AMD64 LINUX_ARM64; do
  [ -n "${!v}" ] || {
    echo "error: $(echo "$v" | tr '[:upper:]' '[:lower:]') checksum not found for ${VERSION}" >&2
    exit 1
  }
done

render() {
  local class_name=$1 out=$2
  cat > "$out" <<EOF
# typed: false
# frozen_string_literal: true

# This file was generated by generate.sh. DO NOT EDIT.
class ${class_name} < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "${VERSION}"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/${TAG}/xiond_${VERSION}_darwin_amd64.tar.gz"
      sha256 "${DARWIN_AMD64}"

      define_method(:install) do
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/${TAG}/xiond_${VERSION}_darwin_arm64.tar.gz"
      sha256 "${DARWIN_ARM64}"

      define_method(:install) do
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/${TAG}/xiond_${VERSION}_linux_amd64.tar.gz"
      sha256 "${LINUX_AMD64}"
      define_method(:install) do
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/${TAG}/xiond_${VERSION}_linux_arm64.tar.gz"
      sha256 "${LINUX_ARM64}"
      define_method(:install) do
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
EOF
  echo "Wrote $out"
}

if [ "$IS_PRERELEASE" = "false" ]; then
  render "Xiond" "Formula/xiond.rb"
else
  echo "Pre-release: leaving Formula/xiond.rb unchanged"
fi
render "XiondAT${MAJOR}" "Formula/xiond@${MAJOR}.rb"
render "XiondAT${CLASS_VERSION}" "Formula/xiond@${VERSION}.rb"
