# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT1801Rc11 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "18.0.1-rc11"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc11/xiond_18.0.1-rc11_darwin_amd64.tar.gz"
      sha256 "16c31834e6412d8dd9e3c9ee21b3c3ce80be6155d2fb52c3db03f38eba4edeed"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc11/xiond_18.0.1-rc11_darwin_arm64.tar.gz"
      sha256 "8598e53cab3c63778e2053a5a1fad39e4731c014717d1d6cd0863b5e132cca17"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc11/xiond_18.0.1-rc11_linux_amd64.tar.gz"
        sha256 "ea60ac85760a2e684bf8b0ea89c185d05c194e34401d263cbfc284e283b5a6a0"

        def install
          bin.install "xiond"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc11/xiond_18.0.1-rc11_linux_arm64.tar.gz"
        sha256 "feaf60f18943d42d54de63d66c1e96743c7cf597f068771962adfb5b2cc9947d"

        def install
          bin.install "xiond"
        end
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
