# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT1801Rc11 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "18.0.1-rc11"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc11/xiond_18.0.1-rc11_darwin_amd64.tar.gz"
      sha256 "c57e947711db46748dd8e3d4cf230e1810dffa8c3c95ea8a4afff6aa9eb80d1d"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc11/xiond_18.0.1-rc11_darwin_arm64.tar.gz"
      sha256 "475d112d7286ff85e09b929a003b0591808a1822f75ef4484d09060f0680dc42"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc11/xiond_18.0.1-rc11_linux_amd64.tar.gz"
        sha256 "33f1b9c72980234d3a3978be28b3e5b8cba80cced073d489d0e5a34b6aa492ad"

        def install
          bin.install "xiond"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc11/xiond_18.0.1-rc11_linux_arm64.tar.gz"
        sha256 "1eaf52f08fd583c3ffaf98b89dfbc81b1eea29e7f0242b81373ab8603772c1a7"

        def install
          bin.install "xiond"
        end
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
