# This file was generated by GoReleaser. DO NOT EDIT.
cask "xiond" do
  version "29.0.1"

  on_macos do
    on_intel do
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_darwin_amd64.tar.gz"
      sha256 "aa481ac926b3c90c77b8481a9de0fbf998788375ce25fd92a655a47110a858fc"
    end
    on_arm do
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_darwin_arm64.tar.gz"
      sha256 "360dcc2717f27a52c6dad69df2e5a38342c62d9e6b4ec74ac3fcf1ee99974453"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_linux_amd64.tar.gz"
      sha256 "0c63da7a6abadb4b6b64a2beda62ea0b0d3098114da76f805cb1ee1c8f9900fa"
    end
    on_arm do
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_linux_arm64.tar.gz"
      sha256 "608880fd067d78902aece0cde1f6cecb3ee751d65e00a35b4c1e6c043621b647"
    end
  end

  name "xiond"
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xiond"

  # No zap stanza required

end
