# This file was generated by GoReleaser. DO NOT EDIT.
cask "xiond" do
  version "29.0.1"

  on_macos do
    on_intel do
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_darwin_amd64.tar.gz"
      sha256 "9fbb92bd0c3b9e207096055793283546fda7fdb1d42fd993b71b33a99c847a94"
    end
    on_arm do
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_darwin_arm64.tar.gz"
      sha256 "855ac7bc917c8464eecb830407aa88b358396020490410463d7eee40151cc25e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_linux_amd64.tar.gz"
      sha256 "714d51aab8cc9fc29e3d6331cf0e2e46ff4b039508e34f3a009fe941f1237dc8"
    end
    on_arm do
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_linux_arm64.tar.gz"
      sha256 "c36a80e25d8c824b34403d698803a58ebec57d84e8cdbb9e8531935c197cc479"
    end
  end

  name "xiond"
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xiond"

  # No zap stanza required

end
