# This file was generated by GoReleaser. DO NOT EDIT.
cask "xiond@31" do
  version "31.0.2"

  on_macos do
    on_arm do
      sha256 "ebc8a7986a810421c762e9f7ae2c71ecd513c1cd76fefa1d78fe2990da713124"
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d25c33c3226a9f49ca9957853371492cd4e9eae055247aa08e41898cf64e0039"
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3a496576d02f416ddb1fa96a6faba9f22f2c0d2a73429086c97539e79e3a4304"
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ae0b548bf6d937d1858fe691dffad420420a25e000ef4ed50d4c7cd643e0305c"
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_linux_amd64.tar.gz"
    end
  end

  name "xiond@31"
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xiond"

  # No zap stanza required
end
