# This file was generated by GoReleaser. DO NOT EDIT.
cask "xiond@30.0.0" do
  version "30.0.0"

  on_macos do
    on_intel do
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_darwin_amd64.tar.gz"
      sha256 "06564d41f0da4a37c7c4f6a40809699bcf208b47d62a493a336eb74cb0fb8f54"
    end
    on_arm do
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_darwin_arm64.tar.gz"
      sha256 "84b0ef5bdb21cccd518eeb2fd97ee6f2933de8b38f36e53fa034b970833d47b2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_linux_amd64.tar.gz"
      sha256 "e723661ce690868410ebf995efb84c26d8b418992ef2d475ab7f27cd969000ae"
    end
    on_arm do
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_linux_arm64.tar.gz"
      sha256 "fb470639317ef4fc04082afb3ba667f108ea8c2a2c41d122781e8191134076a3"
    end
  end

  name "xiond@30.0.0"
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xiond"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xiond"]
    end
  end

  # No zap stanza required

end
