# This file was generated by GoReleaser. DO NOT EDIT.
cask "xiond@29.0.1" do
  version "29.0.1"

  on_macos do
    on_intel do
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_darwin_amd64.tar.gz"
      sha256 "cfb579b8ed8b23ee29003b0d48ad311194cd694d8852b77de30714de43a4d88b"
    end
    on_arm do
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_darwin_arm64.tar.gz"
      sha256 "12b040e1b0db3d9e979eb90270b574f2dec54cc061e40858ccf1d3d08092239a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_linux_amd64.tar.gz"
      sha256 "2146fed34b1cf146ca36e0f0a5dcbed37940d7752b32a5e29bbdd632a7981f6e"
    end
    on_arm do
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_linux_arm64.tar.gz"
      sha256 "37b93cd2cfc620a5b838b718505a63417bb4aed3df118c6d72713435f39ee1cc"
    end
  end

  name "xiond@29.0.1"
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xiond"

  # No zap stanza required

end
