# This file was generated by GoReleaser. DO NOT EDIT.
cask "xiond" do
  version "31.0.2"

  on_macos do
    on_arm do
      sha256 "fa2fd0b577ac17b8755715a7ad046a7e33153cb21c2a216e831655ca2deb00f7"
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fa2c4b91385b35f11cc1c718d5774b87051992a86f8e8fd09a4000fd5520a76f"
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "98ec2c7e47068113a26b367ad3af270873b57f25e26f8456cb7ec5db27f48265"
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5af194eb5f4c0eb65c2ae11609c432e492a47cc659a85e0d0afb0e36e4a7fa2e"
      url "https://github.com/burnt-labs/xion/releases/download/v#{version}/xiond_#{version}_linux_amd64.tar.gz"
    end
  end

  name "xiond"
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xiond"

  # No zap stanza required
end
