# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT16 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "16.0.0"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v16.0.0/xiond_16.0.0_darwin_amd64.zip", using: :homebrew_curl
      sha256 "614b598b6eeb7bb94b4fdcd86733157899ba77e8af40f035ede2d5950905fd3b"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v16.0.0/xiond_16.0.0_darwin_arm64.zip", using: :homebrew_curl
      sha256 "7d34274a666d175d80f5713d6a6b7dd6578312317d9b31ad875213ddc84ec170"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/burnt-labs/xion/releases/download/v16.0.0/xiond_16.0.0_linux_amd64.zip", using: :homebrew_curl
        sha256 "ed8de8b33190c1b3218c447c636f5de3cb5b128409b9178554b079b400625e40"

        def install
          bin.install "xiond"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/burnt-labs/xion/releases/download/v16.0.0/xiond_16.0.0_linux_arm64.zip", using: :homebrew_curl
        sha256 "810705419d29abd5d9911c01f2f2943bbd6520337a1ff84c7382ecbdb1e9c19b"

        def install
          bin.install "xiond"
        end
      end
    end
  end
end
