# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT1801Rc12 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "18.0.1-rc12"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc12/xiond_18.0.1-rc12_darwin_amd64.tar.gz"
      sha256 "357a97b7d134fb7d26cdd47eacce39834303f2caaa62b4a3ae688defb5a30ba3"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc12/xiond_18.0.1-rc12_darwin_arm64.tar.gz"
      sha256 "5b0d3bc898d6d5caae555b491793056681fa00e5626813b90d9223b3ae14ec34"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc12/xiond_18.0.1-rc12_linux_amd64.tar.gz"
        sha256 "c1163a1a1a8c83555e3be3d39714dd73d59ad4fd8e44bdbcdf41feb13d9edad1"

        def install
          bin.install "xiond"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc12/xiond_18.0.1-rc12_linux_arm64.tar.gz"
        sha256 "bdd5a9f888559419ebf2dbb9f91c260c7f0625f35e9eebf526cf7a0f3434d4c7"

        def install
          bin.install "xiond"
        end
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
