# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT6 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "6.0.1"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v6.0.1/xiond_6.0.1_darwin_amd64.tar.gz"
      sha256 "de7f282e0c8965fe0a49ce6d72c9c13576c1a9689bc3aab3a9ea75e53972060d"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v6.0.1/xiond_6.0.1_darwin_arm64.tar.gz"
      sha256 "e737aeb63cf99d84b5900b4826dbf7046da10a51ad304326eeeaf324d4ecb2f2"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v6.0.1/xiond_6.0.1_linux_amd64.tar.gz"
      sha256 "b89bd89b55fae47a8060073be65479bafe3deedd6c9ea9908d56033739f4f4f0"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v6.0.1/xiond_6.0.1_linux_arm64.tar.gz"
      sha256 "8a7ba8e3559da3252e6e96e6b25656ed27aafddd97c9375fb3fba4c6b4b1bab3"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
