# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT6 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "6.0.1"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v6.0.1/xiond_6.0.1_darwin_amd64.tar.gz"
      sha256 "8ddf3588fd7f74bfcbaa067efe901ccd35bd0e1eff288c6ad31f4277e47079bc"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v6.0.1/xiond_6.0.1_darwin_arm64.tar.gz"
      sha256 "6e4da712b02934f5b1dba9706c65e6ff2cee9c4715d72a5355f195eccb2b5b5c"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v6.0.1/xiond_6.0.1_linux_amd64.tar.gz"
      sha256 "ee682464d57a2a6ca9839a7cd6bf09b2817555ef0bd6b80ad5031dac587ec164"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v6.0.1/xiond_6.0.1_linux_arm64.tar.gz"
      sha256 "3c307bfc34437f6f9a64ab17341658e6b96a987b194140996e3d421912c4681b"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
