# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT1401 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "14.0.1"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v14.0.1/xiond_14.0.1_darwin_amd64.tar.gz"
      sha256 "7297cbe4cec16fd0d0172ecf899e76853df7dcd8bca4980d98af8dcd03b0589e"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v14.0.1/xiond_14.0.1_darwin_arm64.tar.gz"
      sha256 "6ae07c65baeec2e3aa147bc3b1dfb593d752a0fa8808129a0347419f70038ac7"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v14.0.1/xiond_14.0.1_linux_amd64.tar.gz"
      sha256 "c4a29e968aee46774c4dd258917f6cfa443f9c852be6f05904a8e7822acfea30"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v14.0.1/xiond_14.0.1_linux_arm64.tar.gz"
      sha256 "d58f95af578edb5ec8fcceae010e70df2d75bc7f5e3b7aef34369d09fd539fa7"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
