# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT1102 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "11.0.2"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v11.0.2/xiond_11.0.2_darwin_amd64.tar.gz"
      sha256 "ea44d7bce6b2c06be7746c2a89679e7522e13fa311208d2ad9b722b1f85d6335"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v11.0.2/xiond_11.0.2_darwin_arm64.tar.gz"
      sha256 "b268a7a3be2ae0c4654de011bea5de42ca7a2946c60a9e6e68b82d3aa0b91ffe"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v11.0.2/xiond_11.0.2_linux_amd64.tar.gz"
      sha256 "612f90b5069ec62e5714636f0c90af679502dc77c0c4d0151b218baaec5d97f7"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v11.0.2/xiond_11.0.2_linux_arm64.tar.gz"
      sha256 "9d07fef53641a41736a736f9f4430a3c777fe8225f5ecec069b8cce8763e2dda"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
