# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT29 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "29.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v29.0.0/xiond_29.0.0_darwin_amd64.tar.gz"
      sha256 "e420e4445ae7c18e778e1f33ee50efe93c8f78b94a15a207f198d60e2131f220"

      define_method(:install) do
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v29.0.0/xiond_29.0.0_darwin_arm64.tar.gz"
      sha256 "26fd2dc2a026f925a4c9158457ff986dd401bb32c165f232d6d1a38d02f5911b"

      define_method(:install) do
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v29.0.0/xiond_29.0.0_linux_amd64.tar.gz"
      sha256 "1b57656d346764919991dce32c53e9db56d4d7658da661d9759ef4378faaf5d9"
      define_method(:install) do
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v29.0.0/xiond_29.0.0_linux_arm64.tar.gz"
      sha256 "fc54a5a030e0bb68bc325a15dd0bb5e70f38dcfadf30c4b44968f65c6933faf4"
      define_method(:install) do
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
