# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT9 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "9.0.2"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v9.0.2/xiond_9.0.2_darwin_amd64.tar.gz"
      sha256 "8b9bfd45f5f9d05e1bc53a46a658b0b194fbe3de8d63186ca3aa008c20ad5fd0"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v9.0.2/xiond_9.0.2_darwin_arm64.tar.gz"
      sha256 "e7bc92fa7cb0bdc2fee3b9ca682c03d4a5294702aac7c10978fb8c7b8631f4de"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v9.0.2/xiond_9.0.2_linux_amd64.tar.gz"
      sha256 "27be3efe7cb6c46a9f8383c31ae85704eb5bf01d39900886f3e5dc4eaa633361"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v9.0.2/xiond_9.0.2_linux_arm64.tar.gz"
      sha256 "28bb191caba1d5ee4695be28ec2bfe8934bb1cc5a5575090b5af54d0d2cb5f14"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
