# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT1701 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "17.0.1"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v17.0.1/xiond_17.0.1_darwin_amd64.tar.gz"
      sha256 "5fba931b3ce5933d4a855a73d8a1c592697722c5d16b6d2df0cc0adfec6375b7"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v17.0.1/xiond_17.0.1_darwin_arm64.tar.gz"
      sha256 "7d3f157d6ae511ec0a1817d99c7aa0bd6c150c1290e2935fa3732d182ad76df0"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v17.0.1/xiond_17.0.1_linux_amd64.tar.gz"
      sha256 "edbbece5edf27115777cfe871abacc9f43e0b6be5d2784253fd16d6dd802708d"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v17.0.1/xiond_17.0.1_linux_arm64.tar.gz"
      sha256 "14a75edbb7c79bc13db0ebc682fef883925f64b32bf4771c182015355b2bd2f4"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
