# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT7 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "7.0.1"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v7.0.1/xiond_7.0.1_darwin_amd64.tar.gz"
      sha256 "cb1a6cfb3750af2fa9fd6c8dfdca34e48a13cd34fef85bf224d8d1a360cf309e"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v7.0.1/xiond_7.0.1_darwin_arm64.tar.gz"
      sha256 "b3645a9b7854556cf3d84f03258ebf0a4bf6ec63115c957cbc6726b943050379"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v7.0.1/xiond_7.0.1_linux_amd64.tar.gz"
      sha256 "9c62d941abb6b99c68384bc4afc8a3f6e3949b16947637ba455e23e04dc36c29"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v7.0.1/xiond_7.0.1_linux_arm64.tar.gz"
      sha256 "b593aa87bc9f4168f5a113c0b3965d5673d0f5452fb11ff14e9eff6b61f7ec73"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
