# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT401 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "4.0.1"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v4.0.1/xiond_4.0.1_darwin_amd64.tar.gz"
      sha256 "856640eafbe5221adf32f1b69e67fb32b4956061aa300c0971ba8f07eb9ef14f"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v4.0.1/xiond_4.0.1_darwin_arm64.tar.gz"
      sha256 "a8f0dfabb907978da3431e6dacfb8dd0ad560d31c0e637d1fa07e995689f278d"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v4.0.1/xiond_4.0.1_linux_amd64.tar.gz"
      sha256 "fe118cc65f51e42cf6790dd9d47072f8d9a938ceed098c8012bec057729a234b"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v4.0.1/xiond_4.0.1_linux_arm64.tar.gz"
      sha256 "75fbd5f314e164a0d82fe1e56fd877f8656bbfae9f6daed2e614e286ef73e7f0"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
