# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT1601 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "16.0.1"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v16.0.1/xiond_16.0.1_darwin_amd64.tar.gz"
      sha256 "1b9891d79985f0ae47b4702adb7c577094239dc2f812349ef38cd917bf84e801"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v16.0.1/xiond_16.0.1_darwin_arm64.tar.gz"
      sha256 "f85f4becb51c219072c359fd37909886268257e2512a7dcd9ced3036f66af4b6"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v16.0.1/xiond_16.0.1_linux_amd64.tar.gz"
      sha256 "12bfe379624d3ddfaa9715de708750385773353d54e838a563796dea084ae1c2"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v16.0.1/xiond_16.0.1_linux_arm64.tar.gz"
      sha256 "0ccf9c4a2c6934643cdd43f2072bb01a099dad43acac97a01299e80566039e26"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
