# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT1700 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "17.0.0"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v17.0.0/xiond_17.0.0_darwin_amd64.zip", using: :homebrew_curl
      sha256 "f8fe47d8a9f831c91c233e6fc757d2c236364d805905df207aa197a53628e06b"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v17.0.0/xiond_17.0.0_darwin_arm64.zip", using: :homebrew_curl
      sha256 "fa15044d4faecf0370cd0efad5fd1095ee7b4bdeb2416cf7b9c18b9cd7422638"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/burnt-labs/xion/releases/download/v17.0.0/xiond_17.0.0_linux_amd64.zip", using: :homebrew_curl
        sha256 "6ec3066e973334e019d66eee77f0557044eb9e7ab723626b66ec88ac11c90d29"

        def install
          bin.install "xiond"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/burnt-labs/xion/releases/download/v17.0.0/xiond_17.0.0_linux_arm64.zip", using: :homebrew_curl
        sha256 "4e85aa63362f983c86c504f1902d9b30c266449eb6c4263394d0b9616a65f086"

        def install
          bin.install "xiond"
        end
      end
    end
  end
end
