# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT2510Rc1 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "25.1.0-rc1"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v25.1.0-rc1/xiond_25.1.0-rc1_darwin_amd64.tar.gz"
      sha256 "08a9e28f958b2764b84cd721e258b4cb2bcda0fd4a7a265fb152e0618c7c0eb0"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v25.1.0-rc1/xiond_25.1.0-rc1_darwin_arm64.tar.gz"
      sha256 "af0e37b3097695914b39cf0dddb5622cec80ad5ffcb3c08b83411cdf380c6a7e"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v25.1.0-rc1/xiond_25.1.0-rc1_linux_amd64.tar.gz"
      sha256 "5e2fa69e9deafc636390c760658c5e69b258cd5a8d0ecc178c0da50cdbb8768b"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v25.1.0-rc1/xiond_25.1.0-rc1_linux_arm64.tar.gz"
      sha256 "ce5c5ef1ab650b1c29cc43c625b4b91a7249d22e9668463917fd40525a7e5803"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
