# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT701 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "7.0.1"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v7.0.1/xiond_7.0.1_darwin_amd64.tar.gz"
      sha256 "5e4bd4ee5946ad55bf7080e6f0f9bbc954802008f1b36390fe784e0f51e17ef6"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v7.0.1/xiond_7.0.1_darwin_arm64.tar.gz"
      sha256 "490b1dbefaee65bc72d6f29fe6259d4810c00b63708349bb718738172c8119a5"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v7.0.1/xiond_7.0.1_linux_amd64.tar.gz"
      sha256 "b2b3d0a3d084c3181cbda5bb4e7cfb13a1eaf30f13273116a9e4c08f5da2b68c"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v7.0.1/xiond_7.0.1_linux_arm64.tar.gz"
      sha256 "4bef7495e47d2bd8d7d71e4978a07ab941f7d24b5729913effd8e805b28c29d9"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
