# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT4 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "4.0.1"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v4.0.1/xiond_4.0.1_darwin_amd64.tar.gz"
      sha256 "32b1de993d75748e18c5485da9c52782f2d8b2dc811c460d7eaea77745284f1c"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v4.0.1/xiond_4.0.1_darwin_arm64.tar.gz"
      sha256 "944eb33d96a37049aad760c439a175b17a243c982d921a47841556cd81759159"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v4.0.1/xiond_4.0.1_linux_amd64.tar.gz"
      sha256 "13dbf35383c99dc37f3fbcf6e85ebb4e836f08962890e0fab293210893e80718"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v4.0.1/xiond_4.0.1_linux_arm64.tar.gz"
      sha256 "4e6b002add8c07d03892338d4125d8446026b5c39228838ba756e348cd249800"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
