# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT802 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "8.0.2"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v8.0.2/xiond_8.0.2_darwin_amd64.tar.gz"
      sha256 "474183a81639af0590aab6252d9c83c0a43dd65d88ca4049d2b3ea64a1f6cfe9"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v8.0.2/xiond_8.0.2_darwin_arm64.tar.gz"
      sha256 "473aa19fd4f7ef26d2d08b6eb2832695ff21fa0005bc25a9862dbdf5951c47ae"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v8.0.2/xiond_8.0.2_linux_amd64.tar.gz"
      sha256 "248a5fa4d817dab7da81dc813054c05ffec4ca603c8dbccfd69e890397f420a9"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v8.0.2/xiond_8.0.2_linux_arm64.tar.gz"
      sha256 "b6a2ac7e289c1562a0a74cb76b7de6c09b3b7194238db50f356d052b8d7d13f2"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
