# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT26 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "26.1.0-rc2"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v26.1.0-rc2/xiond_26.1.0-rc2_darwin_amd64.tar.gz"
      sha256 "5589a7e37846ba8877a8d2678c541385103d64476d2ecf5c05c95ed05552e007"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v26.1.0-rc2/xiond_26.1.0-rc2_darwin_arm64.tar.gz"
      sha256 "e58aa74b678fb407105c7ea08454a3dfce0fd48a0e45b42a2c5ba556fd90ab40"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v26.1.0-rc2/xiond_26.1.0-rc2_linux_amd64.tar.gz"
      sha256 "a053d086bf30af6005adaa92fd8239fc339d394566bd682f7dcf7a0f75017f44"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v26.1.0-rc2/xiond_26.1.0-rc2_linux_arm64.tar.gz"
      sha256 "da8e70f2ab9ed1caa9c217bfb5d3b254b5c257ed35f0059e710d84aa734e703a"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
