# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xiond < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "18.0.1-rc20"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc20/xiond_18.0.1-rc20_darwin_amd64.tar.gz"
      sha256 "aac17504fc187a70a87075be53def7c52aece3cf8d0aab009bd88deace1d9a28"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc20/xiond_18.0.1-rc20_darwin_arm64.tar.gz"
      sha256 "c4c184eb40b050d110dc7d4f6222c7b144f9eb26d53ebafed06ec6a41b376e50"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc20/xiond_18.0.1-rc20_linux_amd64.tar.gz"
        sha256 "ecf22a03f198adf73f7486bdd9803b682bb1b916d12e1a5b5b43d7d4616fbd87"

        def install
          bin.install "xiond"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc20/xiond_18.0.1-rc20_linux_arm64.tar.gz"
        sha256 "e7c46d71723558cb440f27348790c4c8bc00b27d1ad9140aab79eeaa201cc480"

        def install
          bin.install "xiond"
        end
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
