# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT27 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "27.0.0-rc2"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v27.0.0-rc2/xiond_27.0.0-rc2_darwin_amd64.tar.gz"
      sha256 "4d7baaafa1497cd7cebf4d89e5404aa0db7bd6e190cc41a7349e97c2efda9abf"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v27.0.0-rc2/xiond_27.0.0-rc2_darwin_arm64.tar.gz"
      sha256 "126142075c21bd98a7f2599b30ff42620d10743f09957538422992b9551baeec"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v27.0.0-rc2/xiond_27.0.0-rc2_linux_amd64.tar.gz"
      sha256 "157f0afa84c73247373f97047debe24cb768181dc8214d4da16204662e715ffe"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v27.0.0-rc2/xiond_27.0.0-rc2_linux_arm64.tar.gz"
      sha256 "336705c16d327aa34df4e5a60f9f9d9c74ff40a997fa8087ca97d438b4934537"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
