# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xiond < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "29.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v29.0.1/xiond_29.0.1_darwin_amd64.tar.gz"
      sha256 "bdf7ecd3aa136f19eadd46480a4dc1898381d07751ff4091bd624f1eb341a809"

      define_method(:install) do
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v29.0.1/xiond_29.0.1_darwin_arm64.tar.gz"
      sha256 "cb0a29c8135c9348744fcbaa4ea794cc417f708e46abe1c1db099bbcb7d1601f"

      define_method(:install) do
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v29.0.1/xiond_29.0.1_linux_amd64.tar.gz"
      sha256 "c00a269695f32ccd1fbe54f3d7db506fe8576373ece7a54f7e46f423ab4c3312"
      define_method(:install) do
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v29.0.1/xiond_29.0.1_linux_arm64.tar.gz"
      sha256 "33724370cde672d2d6f7d7ca45c54241c15d714e258559b8cab7c37a4a5d40bf"
      define_method(:install) do
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
