# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT2400 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "24.0.0"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v24.0.0/xiond_24.0.0_darwin_amd64.tar.gz"
      sha256 "a14623faa9c44a1ec219b279455d86aada9242f2f10fb7ee76eddf0e9f88ac12"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v24.0.0/xiond_24.0.0_darwin_arm64.tar.gz"
      sha256 "9b6a4ac4f39e03894ed78e422a985729d4ec4347d4761d370f06fa7bdc8824ae"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v24.0.0/xiond_24.0.0_linux_amd64.tar.gz"
      sha256 "f8c4328551f6281b2a5382faf6d94ab4d6da05fd7f99f7f06e2a25732739e9f8"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v24.0.0/xiond_24.0.0_linux_arm64.tar.gz"
      sha256 "5250ced813211527292ac5be621c5ab0c89701838e27935652fa1367ae910487"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
