# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT1801Rc15 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "18.0.1-rc15"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc15/xiond_18.0.1-rc15_darwin_amd64.tar.gz"
      sha256 "b56ec11026d3fb0c893c1cbb57a9d60b258e591b5f17fe8768a57c8ced96b648"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc15/xiond_18.0.1-rc15_darwin_arm64.tar.gz"
      sha256 "d53fb302732e246931f1d5436a6b4bf344135392db401dc379650db8db0ff14d"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc15/xiond_18.0.1-rc15_linux_amd64.tar.gz"
        sha256 "63d730c663939d921b37dd66ede4a3b722b2449748edcafff3b5890883f62ea5"

        def install
          bin.install "xiond"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc15/xiond_18.0.1-rc15_linux_arm64.tar.gz"
        sha256 "6cc498dfb292e3787dfcf1db6ea9886f4f3c9c6e5cd3565cc36a3523cdf6bd37"

        def install
          bin.install "xiond"
        end
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
