# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT18 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "18.0.1-rc13"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc13/xiond_18.0.1-rc13_darwin_amd64.tar.gz"
      sha256 "c7dcd71ea5d70f1ea2c16337aa7a80ba04b2e2f34497f8ba60af3dc342610799"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc13/xiond_18.0.1-rc13_darwin_arm64.tar.gz"
      sha256 "ae0bb593c8593090069493fbb3ca2fca0dcb56cb9c7ad5042fa00e70a83504c8"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc13/xiond_18.0.1-rc13_linux_amd64.tar.gz"
        sha256 "a3dc458b73f2704ce8cfd08997db64ad88876d0b889ad5b689f1cf789c99dd26"

        def install
          bin.install "xiond"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc13/xiond_18.0.1-rc13_linux_arm64.tar.gz"
        sha256 "627390c6ff30cc55ea285e1941b8f9a6fa5b96e27c4aea408fbeb60d4c1e906a"

        def install
          bin.install "xiond"
        end
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
