# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT2100 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "21.0.0"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v21.0.0/xiond_21.0.0_darwin_amd64.tar.gz"
      sha256 "648c88f02b11446e7577ed45ac0b7a7291caa89571a383d561494e81e655e321"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v21.0.0/xiond_21.0.0_darwin_arm64.tar.gz"
      sha256 "019cacc2ee6f1edce24e9f496ff4e1c60400b2d178d83bbc4180f83321386c36"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v21.0.0/xiond_21.0.0_linux_amd64.tar.gz"
      sha256 "801e58300fdfc891037b0b5223b0abe3a675ee0c4247ada3b0a5c0341861fa86"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v21.0.0/xiond_21.0.0_linux_arm64.tar.gz"
      sha256 "04d9101b950ff2ee46e6ad787e465b9cd401b90defae56879d11d13e7bf6045d"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
