# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT26 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "26.0.0-rc1"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v26.0.0-rc1/xiond_26.0.0-rc1_darwin_amd64.tar.gz"
      sha256 "d2889126b4a83b55116d085b4dbb28d9295d21dca91af9acabddf39705a84444"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v26.0.0-rc1/xiond_26.0.0-rc1_darwin_arm64.tar.gz"
      sha256 "4be06ad881bb11ee772a3310d2fda96cd3ffc1c3cd711afe7f133dc713c8ee10"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v26.0.0-rc1/xiond_26.0.0-rc1_linux_amd64.tar.gz"
      sha256 "4d90fea2a4b4324c2719804631d30cd3191ba7140086d35cdef904dcc4f4bc83"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v26.0.0-rc1/xiond_26.0.0-rc1_linux_arm64.tar.gz"
      sha256 "d3b05b7341fdf5f28d25a6a202d3dde7e2a1f9aaa01b5aadce51f95d9be65e67"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
