# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT27 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "27.0.0-rc1"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v27.0.0-rc1/xiond_27.0.0-rc1_darwin_amd64.tar.gz"
      sha256 "13c9adae7f8e3abd99ab598d256d678f921e2a7f503fee2ef2bd969f24edf2ac"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v27.0.0-rc1/xiond_27.0.0-rc1_darwin_arm64.tar.gz"
      sha256 "9e10c18759ed3d4f266b87cf0d174286e7c3a88bf6b477247c428c75e06ac8a4"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v27.0.0-rc1/xiond_27.0.0-rc1_linux_amd64.tar.gz"
      sha256 "c35fef563b98214be12a5c1dc3d1cbc9894381eb4db983f9b2270155fa6af3f5"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v27.0.0-rc1/xiond_27.0.0-rc1_linux_arm64.tar.gz"
      sha256 "7730673ad450691bf5e3c46ebe106dc59c79e2ee82ac59110fc02e4a2d9d7f23"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
