# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT2610Rc1 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "26.1.0-rc1"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v26.1.0-rc1/xiond_26.1.0-rc1_darwin_amd64.tar.gz"
      sha256 "88ee8b7b926618a46af4e6085d097b858d8235fffce7ff44275808bfe39206d9"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v26.1.0-rc1/xiond_26.1.0-rc1_darwin_arm64.tar.gz"
      sha256 "4609d1907a2e8a2b96fadd49952f64236c7d8f90babdde67d8818317cc622a11"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v26.1.0-rc1/xiond_26.1.0-rc1_linux_amd64.tar.gz"
      sha256 "b9230f7d09b4c65527a0ccdff58c99e785e6936110ab1b5b629e300fab5d155c"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v26.1.0-rc1/xiond_26.1.0-rc1_linux_arm64.tar.gz"
      sha256 "9759359918d082589652b22785924b13b992f61bca3b8204e7997a5346b1c7ee"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
