# typed: false
# frozen_string_literal: true

# This file was generated by generate.sh. DO NOT EDIT.
class XiondAT3000 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "30.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v30.0.0/xiond_30.0.0_darwin_amd64.tar.gz"
      sha256 "06564d41f0da4a37c7c4f6a40809699bcf208b47d62a493a336eb74cb0fb8f54"

      define_method(:install) do
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v30.0.0/xiond_30.0.0_darwin_arm64.tar.gz"
      sha256 "84b0ef5bdb21cccd518eeb2fd97ee6f2933de8b38f36e53fa034b970833d47b2"

      define_method(:install) do
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v30.0.0/xiond_30.0.0_linux_amd64.tar.gz"
      sha256 "e723661ce690868410ebf995efb84c26d8b418992ef2d475ab7f27cd969000ae"
      define_method(:install) do
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v30.0.0/xiond_30.0.0_linux_arm64.tar.gz"
      sha256 "fb470639317ef4fc04082afb3ba667f108ea8c2a2c41d122781e8191134076a3"
      define_method(:install) do
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
