# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT28 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "28.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion-security-fix/releases/download/v28.0.1/xiond_28.0.1_darwin_amd64.tar.gz"
      sha256 "eee8623049fca030cf4896eb2574f056baf5daa44aadef84c43e6c24019fe9ad"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion-security-fix/releases/download/v28.0.1/xiond_28.0.1_darwin_arm64.tar.gz"
      sha256 "73847637258a82172045a26025bfe7441ba12745acba457f7b473bda5b063668"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion-security-fix/releases/download/v28.0.1/xiond_28.0.1_linux_amd64.tar.gz"
      sha256 "d038070083cc07ff1e2e6b907087902316c3a2b6a34cf4016db125d2267d43b4"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion-security-fix/releases/download/v28.0.1/xiond_28.0.1_linux_arm64.tar.gz"
      sha256 "d0ee2ea94a17a9aecc190b95e9e21e0084f3999347e1b567c70a9260eda68e2c"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
