# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT1801Rc21 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "18.0.1-rc21"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc21/xiond_18.0.1-rc21_darwin_amd64.tar.gz"
      sha256 "3b64572ea17dd7ad940b16b062607234a40e8d013f3582eb30046cf2104ed425"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc21/xiond_18.0.1-rc21_darwin_arm64.tar.gz"
      sha256 "3d33290fdf2cf36b84adf451ce4f612913658db16e3a3aba8cab8a96a48df4f5"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc21/xiond_18.0.1-rc21_linux_amd64.tar.gz"
        sha256 "05d470ffcce8952a1e97b5a954dc4075e8ad47560222d1e408dc8807c83518f0"

        def install
          bin.install "xiond"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/burnt-labs/xion/releases/download/v18.0.1-rc21/xiond_18.0.1-rc21_linux_arm64.tar.gz"
        sha256 "0cb63325970be374a4be779474a8ca5e275a5dd48939ce381c666df307ae8e9c"

        def install
          bin.install "xiond"
        end
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
